version: '3.3'

services:
    postgres:
        image: postgres:10-alpine

    tests:
        build: .
        depends_on:
            - postgres
        command: bash bin/test
        volumes:
            - ./:/usr/src/app

